### ISSUE TITLE
Love the project. Can't make it though :(

### ISSUE THREAD

**Issue by JordanCheney** [biometrics/likely#1] opened 2013-07-26 00:47 UTC
I saw your link to this from an openbr issue so I read the source code and I think its an awesome project and I would love to assist in any way I can if you would have me. Unfortunately, I can't make the project from git I get the error 

[ 55%] Built target LLVMMCJIT
Scanning dependencies of target LLVMAArch64Utils
make[2]: **\* No rule to make target `llvm/lib/Target/AArch64/AArch64GenSubtargetInfo.inc', needed by`llvm/lib/Target/AArch64/Utils/CMakeFiles/LLVMAArch64Utils.dir/AArch64BaseInfo.cpp.o'.  Stop.
make[1]: **\* [llvm/lib/Target/AArch64/Utils/CMakeFiles/LLVMAArch64Utils.dir/all] Error 2
make: **\* [all] Error 2

I know this is still in the dev phase but I think the Readme said it should compile. Anyways, I figure this is probably pretty far down on the priorities list but whenever you get around to it can you offer some help?

**Comment by jklontz** [comment] 2013-07-26 02:16
This is high on the priority list :) I've only been working on OS X. Are you Windows + MSVC 2012?

**Comment by JordanCheney** [comment] 2013-07-26 16:25
No I did this at home so OS X for me

**Comment by jklontz** [comment] 2013-07-26 17:04
Hmm, I can't seem to replicate :(

**Comment by jklontz** [comment] 2013-08-06 12:51
Resolved in person, unclear what the cause was.

**Comment by JordanCheney** [comment] 2013-08-20 02:25
Josh-

I have continued to look over the project and I would like to write a basic equation to help with my understanding of likely. I was thinking a 1D and then a 2D gaussian function would be sufficiently complex to expand my knowledge. My first thought was to write them both as unary functions following the same basic structure as 'madd', looking at likely.cpp however it doesn't appear that some functionality, like for loops or matrix indexing, is currently supported. Am I overlooking a part of the code that does this, is this a logical next step for development, or is this not the proper way to implement a more complex function? If this is something that needs to be developed I would be happy to write some or all of it to try and gain more understanding of the code. Finally, is this the appropriate forum for questions like this or should I ask elsewhere?

**Comment by jklontz** [comment] 2013-08-20 13:44
Jordan, I'm thrilled with the interest you are expressing in this project, and this is a fine forum for asking questions. The logic required to express convolutions is currently not supported, so it would be tricky to implement a gaussian kernel at this moment. There are some much lower hanging fruit that need to be tackled before doing convolutions, and I would appreciate your help with these if you are willing:
1. Some of the test cases are commented out in `benchmark.cpp`, we need to figure out why these don't pass.
2. Saturated integer arithmetic.
3. Support core math routines: http://www.cplusplus.com/reference/cmath/

**Comment by jklontz** [comment] 2013-08-21 16:56
We now have a mailing list for these discussions! https://groups.google.com/forum/#!forum/likely-dev

**Closed as completed by jklontz** 2013-08-21 16:56 UTC

**Comment by cairobert** [comment] 2013-08-29 05:40
I met the same error. I commented it and some other platform in CMakeLists.txt and it works.
