### ISSUE TITLE
tbb required

### ISSUE THREAD

**Issue by fgenolini** [biometrics/likely#54] opened 2015-04-02 11:22 UTC
On MacOSX 10.10.2, Likely will only build if tbb is installed, even if cmake is configured with no TBB.

src/CMakeFiles/likely_shared.dir/build.make
when linking CXX shared library ../liblikely.dylib
ld: library not found for -ltbb

installing TBB fixes that

1 test fails:
        Start 223: matrix_io.lisp
223/233 Test #223: matrix_io.lisp ..................................................................................***Exception: Other 14.59 sec

Regards,

Francois Genolini

Aberdeen, Scotland

**Comment by jklontz** [comment] 2015-04-02 11:57
Hmm, I can't reproduce this on 10.9.5. Will keep an eye out for it when I upgrade. Seems like a potential issue upstream with OpenCV, as that's were the tbb dependency would be added.

**Comment by jklontz** [comment] 2015-04-03 22:12
I'm closing this one as I can't reproduce it from a clean 10.10.2 image

**Closed as completed by jklontz** 2015-04-03 22:12 UTC
